# Generated by Django 4.2 on 2023-05-12 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise', models.CharField(max_length=255)),
                ('raison_sociale', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=255)),
                ('contact_telephone', models.CharField(max_length=20)),
                ('attestation_fin_stage', models.FileField(blank=True, null=True, upload_to='attestations/')),
                ('rapport_stage', models.FileField(blank=True, null=True, upload_to='rapports/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('nombre_stagiaires', models.PositiveIntegerField(blank=True, null=True)),
                ('date_stage', models.DateField(blank=True, null=True)),
                ('encadreur_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages_encadres', to=settings.AUTH_USER_MODEL)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages_realises', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
