# Generated by Django 4.2 on 2023-05-13 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='encadreur_academique',
        ),
        migrations.AddField(
            model_name='stage',
            name='encadreur',
            field=models.ForeignKey(default=1, limit_choices_to={'type_utilisateur': 'ad'}, on_delete=django.db.models.deletion.CASCADE, related_name='stages_encadreur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stage',
            name='etudiant',
            field=models.ForeignKey(limit_choices_to={'type_utilisateur': 'et'}, on_delete=django.db.models.deletion.CASCADE, related_name='stages_etudiant', to=settings.AUTH_USER_MODEL),
        ),
    ]
