# Generated by Django 4.2 on 2023-05-13 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stage.models
from utilisateur.models import CustomUser

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stage', '0002_remove_stage_encadreur_academique_stage_encadreur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='encadreur',
            field=models.ForeignKey(default=1, limit_choices_to={'type_utilisateur': 'ad'}, on_delete=django.db.models.deletion.CASCADE, related_name='stages_encadreur', to=settings.AUTH_USER_MODEL),
        ),
    ]
