# Generated by Django 4.2 on 2023-05-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='photo_profil',
        ),
        migrations.AddField(
            model_name='customuser',
            name='adresse_mail',
            field=models.EmailField(default='test@test.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cursus',
            field=models.CharField(blank=True, choices=[('CGE', 'Comptabilité et gestion des Entreprises'), ('MCV', 'Marketing comerce vente'), ('BAT', 'Bâtiment'), ('TPU', 'Travaux Publics'), ('ELT', 'Electrotechnique'), ('MSE', 'Maintenance des Systèmes Electronique'), ('FCL', 'Froid et Climatisation'), ('BQF', 'Banque Finance'), ('MEV', 'Management Evenementiel'), ('GMH', 'Gestion Management Hôtelier'), ('CDRI', 'Concepteur Developpeur Reseau internet'), ('QSIR', 'Qualite, Securite,Internet et Reseau'), ('', ''), ('', ''), ('', '')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('GEL', 'Automatique informatique industrielle et Electronique'), ('GTE', 'Génie Thermique,Energie et Environnement'), ('GTR', 'Génie des Télécommunications et Réseaux'), ('GIN', 'Génie informatique'), ('GEC', 'Génie Civil'), ('GEA', 'Gestion des Entreprises et des Administrations'), ('GMP', 'Génie de Mecatronik et productique '), ('IBM', 'Ingénierie Biomédical')], max_length=50, null=True),
        ),
    ]
