# Generated by Django 4.2 on 2023-05-13 20:09

from django.db import migrations, models
import utilisateur.models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0002_remove_customuser_photo_profil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='adresse_mail',
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to=utilisateur.models.generate_filename, verbose_name='Photo de profil'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cursus',
            field=models.CharField(blank=True, choices=[('cursus1', 'Cursus 1'), ('cursus2', 'Cursus 2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('dept1', 'Département 1'), ('dept2', 'Département 2')], max_length=50, null=True),
        ),
    ]
