# Generated by Django 4.2 on 2023-05-13 20:18

from django.db import migrations, models
import utilisateur.models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0003_remove_customuser_adresse_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo_profil',
            field=models.ImageField(default='media\\photos_profil\\pp.png', upload_to=utilisateur.models.generate_filename, verbose_name='Photo de profil'),
        ),
    ]
