# Generated by Django 4.2 on 2023-05-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0004_alter_customuser_photo_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cursus',
            field=models.CharField(blank=True, choices=[('CGE', 'Comptabilite et gestion des Entreprises'), ('MCV', 'Marketing comerce vente'), ('BAT', 'Batiment'), ('TPU', 'Travaux Publics'), ('ELT', 'Electrotechnique'), ('MSE', 'Maintenance des Systemes Electronique'), ('FCL', 'Froid et Climatisation'), ('BQF', 'Banque Finance'), ('MEV', 'Management Evenementiel'), ('GMH', 'Gestion Management Hotelier'), ('CDRI', 'Concepteur Developpeur Reseau internet'), ('QSIR', 'Qualite, Securite,Internet et Reseau'), ('GGE', 'Genie Geomatique'), ('MIP', 'Maintenance industrielle et Productique'), ('IRT', 'Ingenierie des Reseaux et telecommunication'), ('GMIE', 'Gestion et Maintenance des Installations Energetiques'), ('GCF', 'Gestion Comptabilite et Financiere'), ('GMO', 'Gestion et Management des Organisations'), ('BGA', 'Banque Gestionnaire des Actifs'), ('MAN', 'Marketing Numerique')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('GEL', 'Automatique informatique industrielle et Electronique'), ('GTE', 'Genie Thermique,Energie et Environnement'), ('GTR', 'Genie des Telecommunications et Reseaux'), ('GIN', 'Genie informatique'), ('GEC', 'Genie Civil'), ('GEA', 'Gestion des Entreprises et des Administrations'), ('GMP', 'Genie de Mecatronik et productique '), ('IBM', 'Ingenierie Biomedical'), ('GTI', 'Genie Thermique et Energetique Industriel')], max_length=50, null=True),
        ),
    ]
