# Generated by Django 4.2 on 2023-05-14 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0007_stage_customuser_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='date_stage',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
