# Generated by Django 4.2 on 2023-05-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0008_alter_stage_date_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='etudiant',
            field=models.CharField(default='nom test', max_length=255),
        ),
    ]
