# Generated by Django 4.2 on 2023-05-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0009_stage_etudiant'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='owner',
            field=models.CharField(default='pas de proprietaire', max_length=255),
        ),
        migrations.AlterField(
            model_name='stage',
            name='etudiant',
            field=models.CharField(max_length=255),
        ),
    ]
