# Generated by Django 4.2 on 2023-05-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0010_stage_owner_alter_stage_etudiant'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='encadreur',
            field=models.CharField(default="Erreur d'encadreur", max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('chef_dept', 'Chef de département'), ('responsable', 'Responsable de niveau'), ('encadreur', 'Encadreur')], max_length=50, null=True),
        ),
    ]
