# Generated by Django 4.2 on 2023-06-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0014_remove_stage_etudiant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='longitude',
        ),
        migrations.AddField(
            model_name='stage',
            name='cood_gps',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
