# Generated by Django 4.2 on 2023-06-03 20:07

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0015_remove_stage_latitude_remove_stage_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='cood_gps',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
