# Generated by Django 4.2 on 2023-06-04 12:34

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0016_alter_stage_cood_gps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='cood_gps',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
