# Generated by Django 4.2 on 2023-06-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0018_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('chef_dept', 'Chef de département'), ('responsable', 'Responsable de niveau'), ('enca', 'Encadreur')], max_length=50, null=True),
        ),
    ]
