# Generated by Django 4.2 on 2023-05-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='type_utilisateur',
            field=models.CharField(choices=[('ad', 'administration'), ('et', 'etudiant'), ('vis', 'visiteur')], default='vis', max_length=3),
        ),
    ]
