# Generated by Django 4.2 on 2023-05-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0003_customuser_adresse_mail_customuser_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='photos_profil/', verbose_name='Photo de profil'),
        ),
    ]
