# Generated by Django 4.2 on 2023-05-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0004_customuser_photo_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='media/photos_profil/', verbose_name='Photo de profil'),
        ),
    ]
