# Generated by Django 4.2 on 2023-05-12 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0005_alter_customuser_photo_profil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='adresse_mail',
        ),
    ]
