# Generated by Django 4.2 on 2023-05-12 22:56

from django.db import migrations, models
import utilisateur.models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0006_remove_customuser_adresse_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to=utilisateur.models.generate_filename, verbose_name='Photo de profil'),
        ),
    ]
